safe: true
lsi: false
highlighter: pygments
markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: nil
    coderay_css: class
source: .
destination: ./_site
permalink: /examples/:title
exclude: ['README.md', '.gitignore']
name: turfjs
baseurl:
description: main turfjs website
url: http://turfjs.org
